import java.time.LocalDate;
import java.util.List;

public interface AuthorDao {

	/**
	 * Inserts a new author to db
	 * ID is generated by db when inserted
	 * @param author
	 */
	void create(Author author);


	/**
	 * Search for authors by their lastname
	 * @param lastName is not case sensitive
	 * @return list of author objects, empty list if no match
	 */
	List<Author> findByLastName(String lastName);


	/**
	 * @param from localdate.to(YYYY, MM, DD)
	 * @param to localdate.to(YYYY, MM, DD)
	 * @return list of authors in range, empty list if no match
	 */
	List<Author> findByBirthDate(LocalDate from, LocalDate to);


	/**
	 * Updates lastname of author
	 * @param id of the author
	 * @param lastName of author
	 * @return true if success, false if author was not found
	 */
	boolean updateLastName(int id, String lastName);


	/**
	 * Remove by author id
	 * @param id of author
	 * @return true if success, false if author was not found
	 */
	boolean remove(int id);


	/**
	 * Removes all authors which match the lastname, gives feedback how many was removed
	 * @param lastName of author
	 */
	void removeByLastName(String lastName);

}
